### ISSUE TITLE
CLI does not work

### ISSUE THREAD

**Issue by MX-Futhark** [dahuapp/dahu#140] opened 2015-05-20 14:13 UTC
Running the next-major-refactor-WIP version of the CLI (without the modifications since 2015-05-19) provokes a ReferenceError ("window" is not defined)

**Comment by barraq** [comment] 2015-05-21 13:51
@MX-Futhark I started tracking down the bug: the bug comes with the inclusion of modules/sceencast.js in dahuapp.js. So either it is in this file or it is in its dependencies. Could you please start investigating ?

**Comment by MX-Futhark** [comment] 2015-05-21 14:39
@barraq I'm on it, although the problem is difficult to track in the extent that the stacktrace is hardly explicit: currently, running ./gradlew :dahu:cli:run -Pargs="generate something.dahu" displays lines such as "at <anonymous (<eval>:linenumber)"

**Comment by barraq** [comment] 2015-05-21 14:53
I know, we are quite limited... The best approach is to comment out all the dependencies from modules/screencast.js (this should make the CLI work) and then add them back one by one ! (there are seven anyway).

**Comment by MX-Futhark** [comment] 2015-05-22 06:50
From our investigations (and as we suspected before evening opening the issue), the problem comes from handlebar, which references the window object. In other words, the problem comes from every dependency of modules/screencast.js using handlebar, that is : handlebar itself (which isn't used in screencast.js, by the way), modules/compiler.js and modules/helpers/template.js...
The problem being that we do need handlebar to compile the .dahu file.

**Comment by MX-Futhark** [comment] 2015-05-22 12:44
Changing the version of handlebars from 3.0.3 back to 1.3.0 makes the CLI work.

**Comment by barraq** [comment] 2015-05-25 18:14
Ok the problem is now fixed. The problem was that in newest version of Handlebars they check wether or not the `global` object is defined in order to determine if running in "server like" environment (namely without a global `window` object). Since Nashorn, unlike NodeJS, does not defined such global object, Handlebars was using `window` which then led the CLI to crash.
To fix this bug I just defined a default `global` object when booting the CLI.

**Closed as completed by barraq** 2015-05-25 18:14 UTC
Labels: bug, core, CLI, next
